
# Eureka????
# Eureka ??
server:
  port: 10010
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # ?????Eureka Server??????,???true.?????????Eureka Server,????????Eureka Server?????,?????false
    register-with-eureka: false # ??????????Eureka Server,???true.????????Eureka Server,?????false.
    service-url:
      # ???Eureka Server???,??????????????????
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#Eureka Client
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10010/eureka/